Vagrant.configure(2) do |config|
  
  # Use the "webmaster" user for SSH
  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = "webmaster"
    config.ssh.keys_only = false  # enable use of keys in ssh-agent
  end

  config.vm.box = "bento/ubuntu-18.04"

  config.vm.synced_folder ".", "/opt/app/src",
    owner: "www-data",
    group: "www-data",
    mount_options: ["dmode=775"]  # ensure group read/write access for webmaster user

  config.vm.provision "shell" do |s|
    s.path = "./install.sh"
  end
  
end